"""
Skripte NAMENJENE ISKLJUCIVO za DoP Standard uzivo generisanje (main_edu.py).
NE mesati sa lib/scripts.py (Ugasi ton Drive folder) ni sa lib/edu_scripts.py
(stari/drugi edukativni pool) -- ovaj fajl je potpuno odvojen, po izricitom
zahtevu.
"""

EDU_DOP_SCRIPTS = [
    "Balkanci u dijaspori, ako posle 10 sati posla nemaš ni gram motivacije za trening, poslušaj ovo. Nemoj očekivati da ćeš svaki put sam sebe da ložiš kao lud. Mozak je već umoran od donošenja odluka ceo dan. Zato trening mora da bude što jednostavniji za započeti. Otvoriš, neko ti kaže šta radiš, kada radiš i gura te kada počneš da popuštaš. Zato VAMIT-5 ima govornu motivaciju od prve do poslednje sekunde treninga. Ne treba ti još jedan video sa muzikom i ajmooo. Treba ti neko da te vodi kada glava počne da kenja. 7 dana džabe za Balkance preko. Link je u BIO.",
    "Balkanci, ako svaki put krenete jako pa odustanete posle dve nedelje, možda pokušavate da trenirate kao neko ko već godinama trenira. I onda telo kaže: Šta koji đavo radiš? Bolji sistem je da prvo naučiš kontrolu i snagu, onda dodaješ kondiciju, eksplozivnost i rad pod umorom. Tako ne juriš samo da se izubijaš, nego postaješ sposobniji. VAMIT-5 zato ima različite nivoe i metodologiju koja te vodi od početnika do ozbiljno spremnog sportiste. Ako si Balkanac u inostranstvu, probaj 7 dana potpuno besplatno. Link je u BIO.",
    "Balkanci, ako trenirate samo da biste izgledali dobro u majici, normalno je da vam posle nekog vremena dopizdi. Probaj nešto drugo: treniraj zbog sposobnosti. Koliko si jak? Koliko brzo možeš da radiš? Koliko dugo možeš da izdržiš kada ti pluća gore? Koliko možeš da ostaneš pribran kada telo kaže stani? Kada trening postane test sposobnosti, odjednom imaš razlog da se pojaviš. Zato je VAMIT-5 napravljen da gradi snagu, kondiciju, eksplozivnost i mentalnu čvrstinu zajedno. Balkanac si preko? Imaš 7 dana džabe da vidiš da li je to više tvoj fazon. Link je u BIO.",
    "Balkanci u Nemačkoj, Austriji i Švajcarskoj, ako ti trening stalno propadne jer nemaš s kim da ga radiš, slušaj brate ovo. Ne čekaj ortaka koji će od ponedeljka sigurno krenuti, jer ćete obojica ostati na WhatsApp-u do decembra. Uđi u sistem u kojem znaš da postoji ekipa koja radi isto što i ti i koja te gura napred. Ljudi mnogo lakše ostaju dosledni kada osećaju da pripadaju nečemu. Zato VAMIT-5 gradi zajednicu najspremnijih Balkanaca u dijaspori, a ne samo listu ljudi koji su skinuli aplikaciju. Ako hoćeš da treniraš sa svojima, imaš 7 dana potpuno besplatno. Link je u BIO.",
    "Balkanci, ako mislite da morate da imate sat vremena za trening da bi imali rezultat, evo gde si se zajebao. Nemaš problem sa time što nemaš sat vremena. Imaš problem što misliš da trening mora svaki put da izgleda isto. Kratak trening može biti ozbiljan ako ima jasnu strukturu, pravi intenzitet i cilj. Zato nemoj čekati savršen dan kada imaš slobodna dva sata. Radi ono što možeš da završiš danas i uradi kako treba. VAMIT-5 je napravljen za ljude koji rade, imaju porodicu, smene i haos od života, a ipak žele da budu strašno spremni. Imaš 7 dana potpuno besplatno. Link je u BIO.",
    "Najskuplja gastarbajterska greška? Napraviš život za koji si se borio, a onda nemaš telo ni energiju da uživaš u njemu. Radiš 10 sati, jedeš šta stigneš, sedneš i kažeš od sutra treniram. I znaš šta je problem? Kada sebi stalno govoriš MORAM, mozak to počinje da doživljava kao pritisak. Zato probaj da promeniš pitanje iz moram li danas u šta mogu danas da uradim za sebe. Mnogo je lakše krenuti kada osećaš da biraš, a ne da si kažnjen. A ako hoćeš da ti trening već bude spreman bez razmišljanja, VAMIT-5 snima novi trening od 45 minuta svaki dan i za početnike i napredne. Balkanac si preko? Probaj 7 dana džabe. Link je u BIO.",
    "Balkanci u dijaspori, tvoje telo te vozi kroz ceo ovaj život. Na posao, po decu, u prodavnicu, na put, a kako mu vraćaš? Osam sati sedenja, pereca sa buterom preko i govoriš ma dobro sam. Brate, nemoj da se zajebavamo. Mozak mnogo lakše prihvata nešto kada sebi ostaviš osećaj izbora. Zato nemoj MORAM da treniram. Reci: Danas ću da vidim koliko mogu. Odmah druga priča. A VAMIT-5 snima svaki dan potpuno novi trening sa govornom motivacijom sa zajednicom Balkanaca u inostranstvu, pa nema onog smaranja opet isti trening. Imaš 7 dana besplatno. Link je u BIO.",
    "Ako si gastarbajter i stalno čekaš da imaš više vremena, zajebavaš se. Više vremena neće doći. Doći će još posla, još računa, još obaveza. Mozak obožava da odloži neprijatnu stvar za kasnije jer tako odmah dobije malo olakšanje. Zato nemoj sebi reći večeras moram da treniram 60 minuta. Reci samo počinjem 10 minuta. Kad kreneš, otpor već pada. VAMIT-5 ti trening spremi unapred i vodi te glasom kroz njega, pa nemaš šta da smišljaš. Balkanac si preko? Imaš 7 dana džabe. Link je u BIO.",
    "Balkanci, znate zašto stalno počinjete pa odustanete? Zato što svaki put kreneš kao lud. Od ponedeljka treniram pet puta, nema slatkiša, nema gluposti! Izdržiš dve nedelje i onda ode sve dođavola. Mozak mnogo lakše prihvata malu promenu koju možeš ponoviti nego ogroman pritisak preko noći. Zato kreni sa jednom stvari koju možeš da radiš i kada ti je najgori dan. To ti pravi identitet, ne savršen plan. VAMIT-5 snima svaki dan potpuno novi trening tokom cele godine, pa samo otvoriš i kreneš. Samo 45 minuta traje trening. Imaš 7 dana potpuno besplatno. Link je u BIO.",
    "Balkanci, najgora stvar koju možete da uradite posle 10 sati smene? Da legneš i kažeš zaslužio sam da ne radim ništa. Jesi, brate. Ali ako to ponavljaš svaki dan, mozak počne da povezuje umor sa potpunom neaktivnošću. Probaj nešto drugo: posle posla napravi 10 minuta prelaza, tuš, hrana, malo odmora, i onda kreni. Ne moraš da budeš zver svaki dan. Samo nemoj da naučiš sebe da je svaki umor razlog da staneš. VAMIT-5 ima govornu motivaciju kroz ceo trening baš zato što nekad glava prva počne da kenja. 7 dana džabe za Balkance preko. Link je u BIO.",
    "Balkanci preko, pazi na ovu zamku. Radiš kao konj da bi jednog dana imao više slobode, a onda svaki dan toliko crkneš da nemaš energije da koristiš tu slobodu. To se zove loš deal, majstore. Telo se navikava na ono što mu stalno radiš. Ako mu svaki dan daješ samo sedenje i posao, kapacitet za napor pada. Zato mu daj mali signal da još uvek treba da bude jako, brzo i sposobno. Ne treba ti savršen trening. Treba ti dosledan izazov. Zato VAMIT-5 svaki dan snima potpuno novi trening koji možeš samo da otvoriš i odradiš. Balkanac si u inostranstvu? Probaj 7 dana besplatno. Link je u BIO.",
    "Balkanci, ako mrzite trening, možda problem nije u vama. Možda svaki put radite trening koji vam je dosadan kao čekanje u nemačkom Rathaus-u. I onda se pitaš zašto nemaš motivaciju. Mozak voli novinu i osećaj napretka. Zato promeni način na koji treniraš: nemoj svaki put samo juriti isti broj serija i ponavljanja, nego sebi postavi novi izazov. Kada imaš nešto da pobediš, trening dobije smisao. VAMIT-5 zato snima potpuno novi trening svaki dan, 365 dana godišnje, napravljen za zajednicu gastarbajtera. Da ne radiš jedno te isto dok ti se život smuči. 7 dana džabe. Link je u BIO.",
    "Najveća laž koju gastarbajter govori sebi? Kad završim sve obaveze, imaću vremena za sebe. Brate, nikad nećeš završiti sve. Uvek će biti posao, računi, porodica, nešto da popraviš, nešto da kupiš. Zato telo mora da dobije svoje mesto usred haosa, ne tek kada haos prestane. I ne moraš svaki put da budeš maksimalan. Bitno je da ne prekineš vezu sa sobom. VAMIT-5 ti zato svaki dan daje spreman trening i vodi te kroz njega glasom, bez razmišljanja šta sad treba da radiš. Ako si Balkanac preko, imaš 7 dana potpuno besplatno. Link je u BIO.",
]
