"""
Fiksne skripte za EDUKATIVNE (AI anatomija) reels-e. Isti princip kao
lib/scripts.py -- rotiraju se u krug, tekst se NE menja/izmislja, samo se
segmentira i za svaki deo generise odgovarajuci AI anatomski video.
"""

EDU_SCRIPTS = [
    "Znaš ono kada izađeš iz prodavnice sa dve kese, popneš se na treći sprat i staneš ispred vrata kao da čekaš medicinski tim? Onda uđeš unutra, spustiš kese i kažeš sebi: Moram stvarno da krenem da treniram. I onda prođu tri dana, pojavi se obaveza, loš dan, umor, i opet isto. Problem većine ljudi nije što ne znaju šta treba da rade. Problem je što nemaju sistem koji ih svaki dan pokrene. Tvoje telo se menja kada dobija pravi izazov dovoljno dugo. Jači mišići, bolja kondicija i više energije dolaze iz ponavljanja pravih stvari. VAMIT-5 je napravljen da ti ukloni najveću prepreku, da ne moraš svaki dan da smišljaš šta da radiš i kako da se nateraš. Dobijaš strukturiran sistem, novi izazov svaki dan, glas koji te vodi kroz trening od prve do poslednje sekunde i zajednicu ljudi koja prolazi isti put. Jer najteži deo transformacije nije jedan težak trening. Najteži deo je ostati osoba koja se pojavljuje svaki dan. Da li si ajkula ili ribica? Testiraj VAMIT-5 App 7 dana potpuno besplatno. Link je u opisu profila.",

    "Uradi ovo: spusti se u čučanj, zadrži donju poziciju i pokušaj da ostaneš stabilan 30 sekundi. Ako počneš da se treseš riba na suvom, tvoje telo ti nešto govori. Nije problem samo snaga druže već komunikacija između tvog mozga i mišića. Sportisti ne treniraju samo da budu jaki već da telo reaguje brzo kada situacija postane haos. Zato VAMIT-5 trening kombinuje snagu, eksplozivnost, kondiciju i rad pod pritiskom, da napravi telo koje može da reaguje kada više nema idealnih uslova. Testiraj VAMIT-5 App 7 dana besplatno, link je u opisu profila!",

    "VO₂ max znači jednostavno koliko dobro tvoje telo koristi kiseonik kada postane teško. Što je bolji, manje se umaraš, brže se oporavljaš i imaš više energije. Najbolji način da ga podigneš? Intervali. Radi jako 30 sekundi, odmori 30 sekundi i ponovi nekoliko puta. Teraš telo da nauči da radi pod pritiskom. Zato je jedna od 5 faza u VAMIT-5 metodologiji baš VO2 MAX faza, da ne budeš samo neko ko izgleda spremno, nego neko ko stvarno može da izdrži kada postane teško. Novi izazov svaki dan, uz motivaciju od prve do poslednje sekunde treninga. Probaj 7 dana besplatno, link je u opisu profila.",

    "Zašto se raspadneš na HYROX-u iako imaš dobru kondiciju? Mnogi treniraju trčanje i misle da su spremni. Problem nastane kada posle jednog kilometra moraš da guraš, vučeš, nosiš i opet trčiš. Tada ne testiraš samo pluća, nego koliko telo može da proizvodi snagu kada si već umoran. Zato treniraj intervale gde kombinuješ težak rad i brz oporavak. Na primer: kettlebell swing, sprawl, sprint, iskoraci u mestu. Tu telo uči da funkcioniše pod pritiskom. Upravo zato VAMIT-5 kombinuje kettlebells, snagu, eksplozivnost, VO2 MAX i mentalni test kroz 5 specijalnih faza, da budeš najmoćniji kad svi drugi padnu. Probaj VAMIT-5 7 dana besplatno, link je u opisu profila.",

    "Ako si brz u trčanju, ali se raspadneš posle sled push-a, znaš problem. HYROX ne osvaja onaj ko je samo dobar trkač ili samo jak u teretani. Pobeđuje onaj ko može da ponavlja jak rad dok mu je puls na 200. To je sposobnost koju većina ljudi nikad ne trenira. Probaj da spojiš snagu i kondiciju u istom treningu, jer život ti nikad ne daje pauzu između problema. VAMIT-5 je napravljen upravo za taj tip spremnosti, jako telo, jaka pluća i glava koja ostaje mirna kada postane teško. Slobodno testiraj VAMIT-5 App 7 dana potpuno besplatno i uveri se zašto je ovo idealna trening metodologija za tebe.",

    "Misliš da si spreman? Hajde da proverimo. Imaš dobru sliku na Instagramu, ideš u teretanu, možda čak izgledaš bolje od 90% ljudi, ali šta se desi kada ti telo više nema energije? Kada puls ode gore, noge pod vatrom, a glava počne da traži izlaz? Tu se vidi razlika između izgleda spremno i biti stvarno spreman. Pravi test nije ogledalo nego trenutak kada bi najradije stao, a ti ipak nastaviš. VAMIT-5 je napravljen za taj trenutak, da gradi snagu, kondiciju i mentalnu čvrstinu kroz 5 specijalnih faza u svakom treningu: BLOCK, VO2 MAX, PLYO, PUMP i SLOW. Pitanje je samo: da li se usuđuješ? Testiraj VAMIT-5 App 7 dana skroz besplatno. Link je u opisu profila.",

    "Balkanci u dijaspori, ajde da budemo iskreni na minut. Došao si u Nemačku, Austriju, Švajcarsku, zapao u posao, smene, račune, obaveze, i svaki dan kažeš: jao samo ovaj period da prođe, pa ću krenuti. Samo što taj period traje već 5 godina. Za auto imaš vremena da odeš na servis. Za telefon imaš vremena da kupiš novu masku. Za telo koje te nosi svaki dan kažeš ma dobro sam. Nisi ti ostario, majstore. Samo si se malo puno opustio. Onaj lik koji je nekad trenirao, igrao fudbal i imao energije nije nestao. Samo ga moraš ponovo probuditi. VAMIT-5 te zove da uđeš u najveću zajednicu koja pravi najspremnije Balkance na svetu. Imaš čak 7 dana skroz besplatno pristup VAMIT-5 App! Link je u BIO.",

    "Balkanci, znate šta je smešno? Za auto od 20 hiljada evra znaš tačno kada ide mali servis. Znaš koje ulje ide. Znaš koji pritisak treba u gumama. A za svoje telo? Ma dobro sam ja. Brate, tvoje telo nije neki stari bajs koji će samo da radi zauvek. To je mašina koju koristiš svaki dan. Ako ga ne održavaš, počne da gubi snagu. I onda se čudiš kada te umori stepenica, kada nemaš energije i kada se osećaš starije nego što jesi. Servisiraj glavnu mašinu. Sebe. VAMIT-5 te zove da uđeš u najveću zajednicu koja pravi najspremnije Balkance na svetu. Imaš čak 7 dana skroz besplatno pristup VAMIT-5 App! Link je u BIO.",

    "Balkanci preko, ovo će malo da zaboli. Znaš onu staru sliku od pre 10 godina? Ona kada si bio 10 kila lakši, kada si imao više energije i kada si mislio da možeš sve? Znam, i dalje čuvaš tu sliku negde. Ali pitanje je, šta radiš da se vratiš tom liku? Nije problem što si ostario nego što si zamenio akciju za komfor. Posao, kauč, Netflix, grickalice i priča ma nemam vremena. Brate, nemaš vremena za telo koje te nosi svaki dan, ali imaš vremena za tri sata skrolovanja? Ajde da se ne lažemo. Vrati malo zver u sebi. VAMIT-5 te zove da uđeš u najveću zajednicu koja pravi najspremnije Balkance na svetu. Imaš čak 7 dana skroz besplatno pristup VAMIT-5 App! Link je u opisu profila.",

    "Balkanci u Nemačkoj, Austriji i Švajcarskoj, stanite sekund. Znam ovu priču. Došao si preko, krenuo od nule, radio šta god treba, napravio nešto svoje. Svaka čast, ozbiljna stvar. Ali ima jedna stvar koju si možda zaboravio usput. Onaj lik koji je nekada igrao fudbal, trčao, penjao se, izazivao sebe, gde je on? Sada ustaješ, ideš na posao, sediš osam sati, vratiš se kući i kažeš: ma sutra ću. Brate, koliko puta već dolazi to sutra? Tvoje telo nije izgubilo sposobnost. Samo si ga predugo držao na pauzi. Vreme je da ga ponovo pokreneš. VAMIT-5 te zove da uđeš u najveću zajednicu koja pravi najspremnije Balkance na svetu. Imaš čak 7 dana skroz besplatno pristup VAMIT-5 App! Link je u opisu profila.",

    "Balkanci, imam pitanje za vas. Kad si poslednji put uradio nešto gde si pomislio: au brate, nisam znao da još mogu ovo? Ne kada si završio smenu. Ne kada si platio račun. Nego nešto što te podseti da si živ. Problem je što muškarac polako izgubi taj osećaj. Malo po malo. Prvo preskoči trening. Onda nema vremena. Onda posao. Onda deca. I odjednom imaš sve što si želeo, ali nemaš onu energiju koju si imao. E pa majstore, nije gotovo. Samo si pustio telo da se uljuljka. Probudi ga malo. Nije ti telo deda, nego si ga ti tretirao tako. VAMIT-5 te zove da uđeš u najveću zajednicu koja pravi najspremnije Balkance na svetu. Imaš čak 7 dana skroz besplatno pristup VAMIT-5 App! Link je u opisu profila.",

    "Balkanci u dijaspori, moram nešto da vam kažem. Nemoj da se ljutiš, ali znam ovu priču. Došao si preko, radiš kao mašina, 10 sati smena, plaćaš račune, pomažeš familiji, ali tvoje telo? Njega tretiraš kao staru stvar u garaži. Auto pereš, servisiraš, sipaš bolje gorivo. A sebi daš kafu, Butterbrezel i kauč posle posla. Pa onda kažeš: ma brate, godine. Kakve godine? Imaš 35 i ponašaš se kao deda od 75. Telo ti nije propalo. Samo si ga ostavio na leru. Ajde majstore, dosta bilo gledanja starih slika i pričanja nekad sam trenirao. Vrati tog lika nazad. VAMIT-5 je zajednica najspremnijih Balkanaca na svetu, postani jedan od nas. Link je u opisu profila.",

    "Ovo je razlog zašto se muškarci posle 35. godine menjaju. Ne zato što ih godine unište, nego zato što prestanu da se takmiče sa sobom. Nekada su trenirali, igrali sport, izazivali sebe. Onda dođu posao, obaveze i komfor i jednog dana pogledaju staru sliku i kažu: gde je nestao onaj ja? Nije nestao. Samo ga godinama nisi trenirao. Stisni guzove i kreni u akciju majstore.",

    "Najopasnija rečenica koju čovek može da kaže. Ma nisam više mlad. Ta rečenica je tiho odustajanje. Nisi star zato što imaš 35, 40 ili 50 godina. Star si kada prestaneš da tražiš od sebe nešto više. Ima ljudi koji sa 50 godina mogu više nego neki sa 25, jer nisu dozvolili telu da zaboravi šta može. U VAMIT-5 postoje ljudi koji su sa 50 godina progledali, napravili neverovatne rezultate sa svojim telom i umom. Nikad nije kasno.",

    "Balkan ima jedan čudan problem. Ponosi se kada njegov auto ima 300 konja. Priča koliko brzo ide, koliko je jak motor. A onda svoje telo, koje treba da nosi 80 godina, pusti da radi na pola snage. Čovek kupi bolji auto za garažu, ali zaboravi da je njegovo telo jedina mašina koju nikada ne može parkirati i zameniti. Da li i ti znaš takvu osobu?",

    "Jednog dana tvoje dete neće pamtiti koliko si radio. Neće pamtiti koliko mejlova si poslao. Koliko sastanaka si imao. Koliko si bio zauzet. Pamtiće da li si imao energije da trčiš sa njim. Da li si mogao da ga podigneš. Da li si bio prisutan. Ljudi često žrtvuju telo da bi napravili bolji život za porodicu, a onda izgube sposobnost da uživaju u tom životu. Imaš samo jedan život. Iskoristi ga pametno.",

    "Najtužnija stvar koju gledam kod ljudi posle 30. godine. Nije to što imaju stomak. Nije ni što su dobili par kila. Najtužnije je kada počnu da veruju da je normalno da budu umorni svaki dan. Da ih bole leđa. Da nemaju snage kao pre. Da kažu: ma godine su. Nisu godine. To je telo koje je godinama dobijalo isti signal, sedi, čekaj, ne koristi se. Ali imam dobru vest. Telo ne zna koliko imaš godina. Zna samo šta mu ponavljaš svaki dan. Zato reaguj sada. Uđi u VAMIT-5.",

    "Ovo će ti biti jasno kada budeš imao 50 godina. Nećeš želeti samo da izgledaš mlađe. Želećeš da možeš da radiš stvari koje sada uzimaš zdravo za gotovo. Da potrčiš. Da podigneš nešto teško. Da odeš na planinu. Da igraš se sa decom bez da se umoriš posle 10 minuta. Ljudi misle da treniraju zbog izgleda. Ali jednog dana shvate da su trenirali zbog slobode. A zašto ti treniraš?",

    "Svi čekaju ponedeljak da krenu sa treningom, ali telo ne zna za ponedeljak. Svake godine ista priča. Posle leta: krećem ozbiljno. Posle praznika: od januara menjam život. Ali problem nije datum nego što ljudi čekaju trenutak kada će imati motivaciju. A motivacija dolazi tek kada vidiš rezultate. Prvo napraviš malu pobedu. Odradiš trening kada ti se ne radi. Tako nastaje osoba, koja može da se osloni na sebe. Da li si ajkula ili ribica?",

    "Znaš šta je najčudnije kod Balkanca? Za auto će izdvojiti za bolje gume. Za telefon će dati 1000 evra. U stanu će popravljati svaku sitnicu. Ali kada telo počne da šalje signale, ma proći će. Neće. Tvoje telo je jedina stvar koju ne možeš da zameniš kada se pokvari. I najveća greška koju ljudi prave je što počnu da ga popravljaju tek onda kada izgube ono što su imali. Reaguj odmah danas.",

    "Znaš li zašto neki ljudi sa 50 godina izgledaju bolje nego ljudi od 25? Zato što nisu čekali da im telo postane problem. Oni su svaki dan ulagali u nešto što većina uzima zdravo za gotovo. Snaga. Pokret. Kondicija. Energija. Godine nisu ono što te uništi. Nedostatak brige o sebi jeste.",

    "Tvoj budući ja će te jednog dana pitati jedno pitanje. Zašto me nisi napravio jačim dok si mogao? Dok si imao vremena. Dok si mogao da trčiš. Dok si mogao da skačeš. Dok si mogao da izgradiš telo koje ti služi. Ljudi čekaju da izgube zdravlje, da bi ga cenili. Pametni ljudi danas grade telo pre nego što im zatreba. Kreni danas.",

    "Možda nisi umoran od života. Možda si samo izgubio telo koje može da ga prati. Ljudi danas traže više kafe, više odmora, više vikenda, a nekada im samo nedostaje sposobno telo. Telo koje ima snagu, kondiciju i energiju da izdrži tempo koji mu život daje. Problem je što se čovek polako navikne na slabost. Počne da misli da je normalno da ga sve boli, da nema energije i da mu je teško. Nije normalno. To je ozbiljan signal da pomeriš guzicu.",

    "Jednog dana nećeš žaliti što si propustio još jedan izlazak. Žalićeš trenutke kada si znao da možeš više, ali si birao lakši put. Kada si rekao počeću od ponedeljka. Kada si imao 25, 30 ili 40 godina i mislio da imaš beskonačno vremena. Najveća prevara je što mislimo da telo uvek čeka. Ne čeka. Svaki dan ga ili gradiš ili ga puštaš da oslabi. Pitanje nije kako izgledaš danas nego kakvo telo ćeš imati za 10 godina.",

    "Svi žele da izgledaju kao sportisti, ali treniraju kao bodybuilderi iz 1995. Danas ljudi prate NFL igrače, MMA borce, HYROX takmičare i žele taj atletski izgled. Ali onda rade samo sprave, sede između serija, skroluju po telefonu i treniraju mišić po mišić. A problem je što sportisti ne grade telo samo da izgleda jako nego koje može da proizvodi snagu, brzinu i izdrži pritisak. Ako želiš atletsko telo, treniraj kao neko kome telo treba za akciju, ne samo za ogledalo.",

    "Svi sada kupuju pametne satove, ali većina gleda pogrešan broj. Svi gledaju kalorije koje su potrošili, korake i puls tokom treninga. Ali jedan broj ti mnogo više govori koliko si stvarno spreman: VO2 max. To je koliko dobro tvoje telo koristi kiseonik kada postane teško. Dvoje ljudi mogu da imaju isti puls na treningu, ali jedan se oporavi za 30 sekundi, a drugi se raspadne narednih pet minuta. Zato nije poenta samo da treniraš jače već da treniraš telo da se brže vrati i ponovi napor. Sledeći put kada pogledaš sat, nemoj samo gledati koliko si potrošio. Pogledaj koliko si sposoban.",

    "Greška zbog koje 90% ljudi sporije napreduje. Ljudi stalno menjaju trening. Danas jedan program, sutra drugi, sledeće nedelje nova aplikacija. Telo nikad ne dobije dovoljno vremena da postane bolje u nečemu. Zamisliti da učiš jezik i menjaš jezik svaka tri dana. Nikada nećeš postati dobar. Isto je i sa telom. Izaberi sistem, prati napredak i dovoljno dugo ga testiraj. Doslednost pobedi savršen plan koji nikad ne završiš.",

    "Tri stvari koje uništavaju tvoju kondiciju, a verovatno ih radiš svaki dan. Prva stvar, treniraš uvek istim tempom. Telo je pametno, navikne se i prestane da se menja. Druga stvar, odmaraš čim postane neprijatno. Upravo taj trenutak kada želiš da staneš je mesto gde telo uči da bude jače. Treća stvar, treniraš samo ono u čemu si dobar. Ako stalno radiš samo ono što voliš, tvoje slabosti ostaju iste. Probaj sledeći put da ubaciš nešto što ti nije prijatno: kraći sprint, teže serije, vežbe koje traže kontrolu. Ne zato da se uništiš, nego da nateraš telo da se prilagodi. Najspremniji ljudi nisu oni koji nemaju slabosti. Oni su samo ljudi koji su ih pronašli i počeli da ih popravljaju.",
]
