"""
Fiksna lista gotovih skripti (narracija) koje ElevenLabs cita bez izmena.
Rotiraju se redom (state.json pamti sledeci indeks), krug se ponavlja kad
se sve iskoriste.
"""

SCRIPTS = [
    "Koliko puta si krenuo sa treningom i posle nekoliko nedelja izgubio motivaciju jer je sve postalo isto? Isti pokreti, isti treninzi, isti osećaj da samo ponavljaš ono što si već radio. VAMIT-5 je napravljen drugačije. Svaki dan te čeka potpuno novi trening, nova kombinacija izazova i novi način da testiraš svoje telo. Ne postoji 20 treninga koji se vrte mesecima. Postoji 365 novih izazova godišnje. Ali ono što ljudi najviše osete nije samo promena treninga. To je osećaj da nikada nisu sami dok treniraju. Od prve sekunde do poslednjeg ponavljanja, jedinstvena govorna motivacija te vodi kroz ceo trening, podseća te zašto si počeo i gura te kada telo počne da traži kraj. Zato VAMIT-5 nije samo trening. To je sistem koji gradi snažnije, izdržljivije i mentalno čvršće ljude. Pridruži se zajednici najspremnijih Balkanaca na svetu. Komentariši VAMIT i dobijaš 7 dana besplatan pristup kompletnoj VAMIT-5 aplikaciji.",

    "Misliš da si spreman jer možeš da odradiš trening bez problema? Ali šta se dešava kada spojiš snagu, kondiciju i umor u istom trenutku? Tu većina ljudi prvi put vidi gde se stvarno nalazi. Možeš da budeš jak u teretani, možeš da imaš odličnu tehniku u sportu, možeš čak i da izgledaš kao neko ko trenira. Ali kada puls ode visoko, kada mišići počnu da se pune umorom i kada mozak počne da traži pauzu, tada vidiš koliko stvarno možeš. Upravo za taj trenutak je stvoren VAMIT-5. Kroz svaki trening prolaziš kroz različite izazove koji teraju tvoje telo da radi kao jedna celina. Počinješ sa kettlebellsima, gradiš snagu i kontrolu kroz pokrete koji traže ceo organizam. Zatim dolazi trenutak kada disanje postaje teže, kada moraš da pronađeš novi ritam i nastaviš iako telo šalje signal da usporiš. Posle toga dolazi deo gde brzina, eksplozija i kontrola pokreta pokazuju koliko si stvarno sposoban. A onda trenutak kada više nemaš gde da se sakriješ, kada ostaje samo tvoja disciplina i odluka da završiš ono što si počeo. Zato ljudi posle prvih VAMIT-5 treninga često kažu isto: Mislio sam da sam spreman, dok nisam probao ovo. VAMIT-5 ti daje priliku da testiraš gde se stvarno nalaziš i da izgradiš sposobnost da budeš najmoćniji onda kada drugi počnu da padaju. Komentariši VAMIT i dobijaš 7 dana besplatan pristup kompletnoj VAMIT-5 aplikaciji.",

    "Najmoćniji ljudi nisu oni koji izgledaju spremno kada je sve lako. Pravi test dolazi kada telo počne da se umara, kada noge postanu teške, kada disanje postane borba i kada većina ljudi počne da traži način da uspori. Upravo tada vidiš šta si stvarno izgradio. VAMIT-5 je stvoren za taj trenutak. Svaki trening je napravljen da te provede kroz različite situacije u kojima telo mora da pronađe način da nastavi. Kreneš snažno sa kettlebellsima, radiš pokrete koji traže snagu, stabilnost i kontrolu celog tela. Kako trening teče, sve više osećaš pritisak, puls raste, mišići se umaraju, ali ti učiš da ostaneš fokusiran i da zadržiš kvalitet pokreta. Dolazi trenutak kada više nije pitanje koliko si jak, nego koliko dugo možeš da ostaneš pod kontrolom kada postane teško. Tu se gradi razlika. Jer u sportu, poslu i životu najveći izazovi ne dolaze kada imaš savršene uslove već kada si umoran, kada nemaš više rezervu i kada moraš da pokažeš ko si. VAMIT-5 je napravljen da budeš najmoćniji upravo tada, kada drugi počnu da padaju. Probaj VAMIT-5 potpuno besplatno 7 dana. Link je u opisu profila!",

    "Mnogi ljudi treniraju samo da bi promenili izgled u ogledalu, ali postoji velika razlika između tela koje samo izgleda snažno i tela koje je stvarno sposobno. VAMIT-5 je napravljen za ljude koji žele mišiće, ali i kontrolu, eksploziju i kondiciju koja ide uz taj izgled. Kettlebell trening gradi snagu kroz ceo pokret, rad sa sopstvenom težinom tera telo da koristi svaki mišić, a intenzitet te uči da ostaneš jak i kada postane teško. Jer pravo atletsko telo nije samo veće nego je snažno, brzo, izdržljivo i spremno za svaki izazov. Bilo da si muškarac koji želi moćniji izgled ili žena koja želi čvrsto, oblikovano i sposobno telo, VAMIT-5 ti daje sistem koji gradi sve zajedno. Probaj VAMIT-5 potpuno besplatno 7 dana. Link je u opisu profila!",

    "Postoji trenutak u svakom VAMIT-5 treningu kada telo više nije sveže. Kada mišići peku, disanje postane teško i kada ti mozak kaže da usporiš. Upravo taj trenutak većina ljudi pokušava da izbegne, a upravo tu se gradi najveća promena. Kroz kettlebell, eksplozivne pokrete i izazove visokog intenziteta učiš svoje telo da ostane pod kontrolom kada pritisak raste. Ne treniraš samo ruke, noge i pluća već gradiš sposobnost da ostaneš miran kada nije lako. To je razlika koju osećaš i van treninga, jer disciplina koju izgradiš dok se boriš sa poslednjim minutima postaje deo tebe. VAMIT-5 je stvoren da budeš najmoćniji kada drugi počnu da padaju. Komentariši VAMIT i dobijaš 7 dana besplatan pristup kompletnoj VAMIT-5 aplikaciji.",

    "Većina fitnes programa te tera da biraš jednu stvar. Ili gradiš mišiće, ili radiš kondiciju, ili treniraš eksplozivnost. Ali stvarno sposobno telo ne funkcioniše tako. Ono mora da bude snažno, brzo, izdržljivo i spremno. VAMIT-5 spaja kettlebell snagu, trening sa sopstvenom težinom i različite intenzitete rada kako bi izgradio kompletnu fizičku sposobnost. Želiš jače noge, čvršće telo, bolju kondiciju i izgled sportiste? Sve to ide zajedno kada treniraš pametno. Nije bitno da li si početnik koji tek kreće ili sportista koji traži novi izazov. Svaki trening je novi test koji te tera da postaneš bolja verzija sebe. Jer cilj nije samo da izgledaš kao sportista već da se tako i osećaš. Probaj VAMIT-5 aplikaciju potpuno besplatno 7 dana. Link je u opisu profila!",

    "Možeš imati velike mišiće, ali šta se dešava kada treba da se krećeš brzo, reaguješ eksplozivno i zadržiš snagu kada si umoran? Tu se vidi prava spremnost. VAMIT-5 ne gradi samo izgled tela, već sposobnost tog tela da radi. Kettlebell pokreti grade snagu kroz celo telo, eksplozivni izazovi razvijaju brzinu i kontrolu, a intenzivni intervali te uče da ostaneš efikasan kada puls ode visoko. Zato VAMIT-5 koriste ljudi koji žele više od klasičnog treninga. Sportisti koji žele dodatni nivo, rekreativci koji žele da se osećaju sposobno i ljudi koji žele telo koje izgleda moćno jer je zaista moćno. Izgradi telo koje ne samo da izgleda spremno, nego može da reaguje kada je potrebno. Komentariši VAMIT i dobijaš 7 dana besplatan pristup kompletnoj VAMIT-5 aplikaciji.",

    "Najveća promena koju ljudi osećaju kroz VAMIT-5 nije samo kada vide više mišića ili bolju formu u ogledalu, već trenutak kada shvate da mogu više nego što su mislili. Kada završe trening koji im je delovao nemoguć. Kada podignu veću težinu, kada izdrže duže, kada ostanu u borbi još nekoliko sekundi. VAMIT-5 je napravljen da razvije celo telo i ceo karakter kroz 365 različitih izazova. Svaki trening kombinuje snagu, kondiciju, eksplozivnost i mentalnu izdržljivost kako bi gradio osobu koja je spremna za pritisak. Jer najbolje telo nije samo ono koje izgleda dobro već ono kome veruješ. Bilo da želiš više mišića, bolju kondiciju ili moćniji atletski izgled, VAMIT-5 te vodi kroz taj proces. Probaj kompletan VAMIT-5 sistem 7 dana besplatno. Link je u opisu profila!",

    "Možda želiš više mišića. Možda želiš da izgledaš atletski. Možda želiš više snage, bolju kondiciju ili da konačno osećaš da imaš kontrolu nad svojim telom. Problem je što većina treninga razvija samo jedan deo. VAMIT-5 gradi sve zajedno. Kettlebell trening za snagu i mišiće, eksplozivni pokreti za brzinu i moć, intenzivni izazovi za kondiciju i momenti kada moraš da pobediš sopstvenu glavu. A kroz ceo trening nisi prepušten sam sebi. Od zagrevanja do poslednje sekunde, govorna motivacija te vodi kroz svaki izazov i pomaže ti da izvučeš maksimum iz sebe. Svaki dan dobijaš novi trening jer telo napreduje kada dobija nove izazove, a ne kada ponavlja isto iznova. VAMIT-5 gradi ljude koji ne žele samo da izgledaju spremno, već žele da budu spremni. Testiraj 7 dana potpuno besplatno. Link je u opisu profila!",

    "Najveće promene se ne dešavaju kada treniraš jednom jako. Dešavaju se kada imaš sistem koji te tera da se pojaviš svaki dan i postaneš bolji. Zato je nastao VAMIT-5. Da napravi zajednicu ljudi koji žele da budu među najspremnijima na Balkanu. Ljudi koji žele snažno telo, moćan atletski izgled i mentalitet osobe koja ne odustaje kada postane teško. Svaki dan snimamo potpuno novi trening, jer ne verujemo u rutinu koja se samo ponavlja. Verujemo u nove izazove koji te teraju da se prilagodiš i napreduješ. Uz jedinstvenu govornu motivaciju koja te prati od prvog do poslednjeg pokreta, svaki trening postaje iskustvo kroz koje prolaziš sa nekim ko te gura napred. Ovo nije samo aplikacija sa treninzima već pokret Balkanaca širom sveta koji žele da budu spremniji nego juče. Pridruži se VAMIT-5 zajednici. Komentariši VAMIT i dobijaš 7 dana besplatan pristup kompletnoj VAMIT-5 aplikaciji.",

    "Postoji trenutak na svakom ozbiljnom treningu kada više nemaš savršen osećaj u telu. Kettlebell postaje težak, disanje se ubrzava, mišići gore i glava počinje da traži razlog da usporiš. Upravo tada dolazi pitanje koje postavljamo u VAMIT-5: da li si ajkula ili ribica? Da li ćeš stati čim postane neprijatno ili ćeš naučiti da ostaneš miran i nastaviš dalje? VAMIT-5 te svaki dan vodi kroz nove izazove snage, kondicije, eksplozivnosti i mentalne izdržljivosti. Uz jedinstvenu govornu motivaciju koja te prati od prvog pokreta do poslednje sekunde treninga, nikada nisi sam u borbi. Svaki dan te čeka novi trening jer telo napreduje kada dobija nove izazove. 365 dana novih treninga, novih testova i novih prilika da postaneš spremniji nego juče. Pridruži se VAMIT-5 zajednici. Komentariši VAMIT i dobijaš 7 dana besplatan pristup kompletnoj VAMIT-5 aplikaciji.",

    "Želiš telo koje izgleda snažno kada se pogleda u ogledalo? Onda moraš da izgradiš više od mišića. Prava atletska forma dolazi kada tvoje telo može da uradi ono što izgleda da može. Kada imaš snagu da podigneš težinu, eksplozivnost da se krećeš brzo, kondiciju da izdržiš do kraja i mentalitet da nastaviš kada postane teško. VAMIT-5 kombinuje kettlebell trening, vežbe sa sopstvenom težinom i različite izazove koji grade kompletno telo. Svaki trening je drugačiji, jer nema ponavljanja istih rutina mesecima. Svaki dan dobijaš novi izazov koji te tera da se prilagodiš i napreduješ. A kada dođe najteži deo treninga, tu je naša jedinstvena govorna motivacija koja te vodi, podseća zašto si počeo i gura te do poslednjeg pokreta. Za muškarce i žene koji žele snažno, moćno i atletsko telo. Da li si ajkula ili ribica? Testiraj sebe. Link je u opisu profila!",

    "Većina ljudi odustane kada trening prestane da bude prijatan. Ali upravo tada počinje deo koji menja tvoje telo i tvoj karakter. VAMIT-5 je napravljen za ljude koji žele više od obične rutine. Ljude koji žele više snage, više energije, više samopouzdanja i telo koje može da odgovori kada život postavi izazov. Svaki dan snimamo potpuno novi trening, jer nema smisla da telo stalno dobija isti signal. 365 dana godišnje imaš novi test koji možeš da savladaš. Kroz ceo trening prati te glas koji te vodi od zagrevanja do poslednje sekunde, jer najteži trenuci dolaze kada si već umoran i tada ti treba pravi sistem. Na kraju svakog treninga ostaje samo jedno pitanje: kada postane teško, kakva osoba postaješ? Da li si ajkula ili ribica? Postani deo zajednice najspremnijih Balkanaca na svetu. Probaj VAMIT-5 potpuno besplatno 7 dana. Komentariši VAMIT i dobijaš 7 dana besplatan pristup kompletnoj VAMIT-5 aplikaciji.",

    "Ako želiš više mišića, slušaj ovo. Većina ljudi odmah razmišlja samo o težini koju podiže. Ali postoji još jedan faktor koji mnogi ignorišu, a to je kvalitet rada. Tvoje telo ne zna koliko je vežba izgledala impresivno. Ono oseća koliko je napora dobilo, koliko kontrole imaš i koliko dobro koristiš mišiće kroz pokret. Zato neko može godinama da trenira, a da izgleda isto, dok neko sa pametnim sistemom napravi ogromnu promenu. Mišići rastu kada telo dobije razlog da se prilagodi. To znači dovoljno intenziteta, dobru tehniku, progresiju i oporavak. Nije poenta samo da podigneš više, već da napraviš telo koje postaje sposobnije iz nedelje u nedelju.",

    "Možeš imati dobar izgled, vidljive mišiće i solidnu snagu, a da se potpuno raspadneš kada trening traje duže od nekoliko minuta. Razlog je što telo ima više različitih sposobnosti. Mišićna snaga je samo jedna od njih. Možeš biti jak u jednom pokretu, ali ako tvoje telo ne zna da koristi tu snagu kada si umoran, brzo dolazi do pada. Zato sportisti treniraju kombinaciju snage, kondicije i rada pod pritiskom. Cilj nije samo da napraviš veliki mišić, već da taj mišić može da radi kada ti puls ode visoko i kada nemaš savršene uslove. Pravo spremno telo može da proizvede snagu, da se brzo kreće i da nastavi kada postane teško. Zato najbolji treninzi ne testiraju samo koliko možeš kada si odmoran, nego koliko možeš kada si već umoran.",

    "Mnogi ljudi misle da je najbolji trening kada si najjači. Kada imaš najviše energije. Kada sve ide savršeno. Ali sport se često odlučuje u trenutku kada to više nije slučaj. Fudbaler u poslednjem minutu utakmice, borac u trećoj rundi, vojnik posle dugog napora, niko od njih ne koristi telo kada je potpuno odmorno. Zato postoji trening pod umorom. Telo mora da nauči da zadrži kontrolu kada puls raste, kada koncentracija pada i kada je lakše napraviti grešku. To je razlog zašto ozbiljan trening ne gradi samo mišiće već sposobnost da ostaneš funkcionalan kada situacija postane teška.",

    "Jedan od najvećih razloga zbog kojih ljudi prestanu da napreduju je što telo više ne dobija novi izazov. Ako svaki trening izgleda isto, telo vrlo brzo nauči šta ga čeka. Ne mora više da se menja istim tempom. Zato napredak zahteva promenu stimulusa. Nekada je potrebno više snage, nekada više brzine, nekada veća izdržljivost ili kontrola pod pritiskom. Telo se menja kada mora da rešava nove probleme. Zato vrhunski sportisti ne rade isti trening svaki dan već stalno traže novi način da pomere granicu.",

    "Postoji razlog zašto dva čoveka mogu da rade isti trening, sa istom težinom i istim brojem ponavljanja, ali jedan napreduje mnogo više. Razlika često nije u genetici već u sposobnosti da ostanu dosledni kada nestane motivacija. Telo će mnogo puta poslati signal da usporiš. To je normalan mehanizam zaštite. Ali kroz pametan trening kao što je VAMIT-5, učiš da razlikuješ pravi problem od trenutka kada samo želiš da odustaneš. Tu se gradi mentalna čvrstina. Ne kroz citate i motivacione poruke, nego kroz hiljade malih odluka kada biraš da završiš ono što si počeo.",
]
